DROP TABLE type_one;
DROP TABLE type_two;
CREATE TABLE type_one (id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, version INTEGER DEFAULT 1, record_add_ts TIMESTAMP, record_update_ts TIMESTAMP);
CREATE TABLE type_two (id INTEGER GENERATED BY DEFAULT AS IDENTITY, version INTEGER DEFAULT 1, effective_ts TIMESTAMP, expiry_ts TIMESTAMP);

INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO type_one (record_add_ts, record_update_ts) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
INSERT INTO type_two (effective_ts, expiry_ts) VALUES (CURRENT_TIMESTAMP, '2999-12-31 23:59:59');
